### ISSUE TITLE
Incorrect type for `error`

### ISSUE THREAD

**Issue by talentlessguy** [spectrexyz/use-nft#128]
`error` is not an object, it's an array of errors:

![image](https://user-images.githubusercontent.com/35937217/126894437-02549472-ebf2-4e05-81a5-785a5397ea2f.png)

**Comment by bpierre** [comment]
Is it with the `ethereum` fetcher? And would you mind providing the failing example? Thanks :pray:

**Comment by talentlessguy** [comment]
@bpierre hello, no, this happens with `ethers`

the reproduction is this:

1. Install hardhat and launch it on `hardhat` network (not localhost).
2. Connect to a wallet but with a wrong network (at least this error happened to me when I was launching `hardhat` instead of `localhost`).
3. Write this:

```ts
import React, { useEffect } from 'react'
import { Contract, utils } from 'ethers'
import { useNft, NftProvider } from 'use-nft'


// other code  ...

function NFT() {
  const { loading, error, nft } = useNft(contractAddress, '1')

  // nft.loading is true during load.
  if (loading) return <>Loading…</>

  // nft.error is an Error instance in case of error.

  if (error || !nft) return <>{error.message}</>

  // You can now display the NFT metadata.
  return (
    <section>
      <h1>{nft.name}</h1>
      <img src={nft.image} alt="" />
      <p>{nft.description}</p>
      <p>Owner: {nft.owner}</p>
      <p>Metadata URL: {nft.metadataUrl}</p>
    </section>
  )
}
```

4. See error

The error itself is easy to fix and is a developer's than user's problem but would be cool to have a type check if error is an array

**Comment by bpierre** [comment]
I can reproduce, thanks!

This is due to https://github.com/spectrexyz/use-nft/pull/90, where I didn’t realize `promiseAny()` was returning an array to simulate an [`AggregateError`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/AggregateError).
