### ISSUE TITLE
 Can`t get an image using  useNft or fetchNft

### ISSUE THREAD

**Issue by OlehX** [spectrexyz/use-nft#175]
Try to get image data from NFT URI, eg: `eip155:1/erc721:0xa3b7cee4e082183e69a03fc03476f28b12c545a7/5566`. There is an issue for Brave browser and in a case with Chrome everything is ok. I try to get data using `useNf()` hook and `fetchNft()` function with the same result.
![image](https://user-images.githubusercontent.com/16556962/154723412-4cdeb4a8-2b48-4007-beab-3d008992aa0b.png)

Could you please add Brave browser supporting to your lib?

**Comment by bpierre** [comment]
Hi, Brave should be supported, it works here: https://codesandbox.io/s/use-nft-issue-175-tjr7bb

If it still doesn’t work for you, could you please provide an example so I can reproduce your setup, and reopen this issue? Thanks!
