### ISSUE TITLE
When using OpenSea Polygon Minting Contract, no NFT image is found

### ISSUE THREAD

**Issue by kolbis** [spectrexyz/use-nft#176]
When using OpenSea Polygon Minting Contract `0x2953399124F0cBB46d2CbACD8A89cF0599974963`, no NFT image is found.
For example, this NFT on open sea:

```
https://opensea.io/assets/matic/0x2953399124f0cbb46d2cbacd8a89cf0599974963/104266429279353206028968205808007262092071789057064791600420254975229853433857
```

is using smart contract `0x2953399124F0cBB46d2CbACD8A89cF0599974963` and token `104266429279353206028968205808007262092071789057064791600420254975229853433857`
yet, useNFT is unable to find the image

**Comment by bpierre** [comment]
Hi, I tried with the Alchemy API through the Ethers provider, it seems to work:

https://codesandbox.io/s/shy-glade-0y6jzz?file=/src/App.js

Note that it’s using the version published with the `next` tag (`use-nft@0.11.0-rc.0`), but it should work with the current stable too.

If you have a different setup, could you please provide an example? Thanks!

**Comment by bpierre** [comment]
@kolbis I am closing this issue, please reopen if the example doesn’t fix your issue :slightly_smiling_face:

**Comment by kolbis** [comment]
In the example you added matic provider since you know in advanced that the NFT is on polygon.

```
const fetcher = [
  "ethers",
  {
    provider: new providers.AlchemyProvider(
      "matic",
      "pFcGSiHgfuWob6xxXN3p4ywQWbDcoSBy"
    )
  }
];
```

What if I need to have some NFTs taken from polygon and others from eth mainnet?
How would you setup such use case?

**Comment by bpierre** [comment]
I would do it this way: https://codesandbox.io/s/use-nft-issue-176-2-kspiyj

**Comment by kolbis** [comment]
Thanks you for this :)
works like a charm

**Comment by bpierre** [comment]
Cool :)
