### ISSUE TITLE
Module not found error

### ISSUE THREAD

**Issue by ctrlc03** [spectrexyz/use-nft#181]
Hi there,

I am having some issues importing use-nft. Here is the error I get:

```
Compiled with problems:

ERROR in ./node_modules/use-nft/dist/index.js 5678:53-60

Module not found: Error: Can't resolve 'process/browser' in '/path/node_modules/use-nft/dist'
Did you mean 'browser.js'?
BREAKING CHANGE: The request 'process/browser' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.
```

I am using:

* React ^18.1.0
* npm 8.12.1
* node v16.14.0

The app was created using React-Create-App. 

Has anyone got the same error and found a solution? Thanks.

**Comment by bpierre** [comment]
Hi, do you have the possibility to move to a bundler like [vitejs.dev](https://vitejs.dev/), [Parcel](https://parceljs.org/) or [esbuild](https://esbuild.github.io/)? CRA [doesn’t seem to be actively maintained anymore](https://github.com/facebook/create-react-app/issues/11180) (even though the React documentation still recommends it), and seems to have issues with ESM only modules.

If not possible, could you please reproduce the issue on a repo? Thanks!

**Comment by ctrlc03** [comment]
I've switched to parcel and it works perfectly. Thank you
